WITH RECURSIVE OUTS AS (
    SELECT 0 AS N

    UNION ALL

    SELECT N+1
    FROM OUTS
    WHERE N < 23)

SELECT O.N AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM OUTS O
LEFT JOIN ANIMAL_OUTS A ON O.N = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR ASC